modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
updateJSONURL="${mod_updatejson}"
displayURL="${mod_url}"
logoFile="mininggadgets-logo.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

#forge
[[dependencies.mininggadgets]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

#minecraft
[[dependencies.mininggadgets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
